#Hugo configuration
title = "23dfsgfd"
baseURL = "https:\/\/324rfdg.asdf.wer"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
